#!/usr/bin/env bash
# ==============================================================================
# Network Stack Installer
# Tested on: Ubuntu Server 25.x minimal (fresh install)
#
# Containers: NPMplus, Technitium DNS, Uptime Kuma, WireGuard, Wireshark, Homarr, Authentik
#
# Usage: sudo bash install.sh
# ==============================================================================

set -euo pipefail

[[ $EUID -ne 0 ]] && { echo "[!] Please run as root: sudo bash $0"; exit 1; }

COMPOSE_DIR="/home/networker"
DATA_DIR="/home/networkder_data"

SERVER_IP=$(hostname -I | awk '{print $1}')
echo "[i] Detected server IP: ${SERVER_IP}"

# pipefail-safe password generator
randpw() {
  local pw
  pw=$(set +o pipefail; cat /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 24)
  printf '%s' "${pw}"
}

# ==============================================================================
echo ""
echo "== 1. Installing prerequisites =="

export DEBIAN_FRONTEND=noninteractive

apt-get update -y -qq
apt-get install -y -qq \
  ca-certificates \
  curl \
  gnupg \
  lsb-release \
  wget \
  net-tools \
  iptables \
  iproute2 \
  ufw

echo "[OK] Prerequisites installed"

# ==============================================================================
echo ""
echo "== 2. Installing Docker =="

if command -v docker &>/dev/null; then
  echo "[OK] Docker already installed -- $(docker --version)"
else
  for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
    apt-get remove -y "$pkg" &>/dev/null || true
  done

  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc

  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu \
$(. /etc/os-release && echo "${VERSION_CODENAME}") stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null

  apt-get update -y -qq
  apt-get install -y -qq \
    docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin

  systemctl enable docker &>/dev/null
  systemctl start docker
  echo "[OK] Docker installed"
fi

docker compose version &>/dev/null && echo "[OK] Docker Compose present"

# ==============================================================================
echo ""
echo "== 3. Freeing port 53 (disabling systemd-resolved stub listener) =="

mkdir -p /etc/systemd/resolved.conf.d

cat > /etc/systemd/resolved.conf.d/no-stub.conf <<RESOLVED
[Resolve]
DNSStubListener=no
DNS=1.1.1.1 8.8.8.8
RESOLVED

systemctl restart systemd-resolved
ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

echo "[OK] systemd-resolved stub listener disabled, port 53 is free"

# ==============================================================================
echo ""
echo "== 4. Configuring kernel for WireGuard =="

modprobe wireguard    2>/dev/null || true
modprobe iptable_nat  2>/dev/null || true
modprobe ip6table_nat 2>/dev/null || true

sysctl -w net.ipv4.ip_forward=1              > /dev/null 2>&1 || true
sysctl -w net.ipv6.conf.all.forwarding=1     > /dev/null 2>&1 || true
sysctl -w net.ipv4.conf.all.src_valid_mark=1 > /dev/null 2>&1 || true

cat > /etc/sysctl.d/99-network-stack.conf <<SYSCTL
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
net.ipv4.conf.all.src_valid_mark=1
SYSCTL
sysctl --system > /dev/null 2>&1 || true

echo "[OK] IP forwarding enabled and persisted"

# ==============================================================================
echo ""
echo "== 5. Creating directory structure =="

mkdir -p "${COMPOSE_DIR}"

for d in \
  "${DATA_DIR}/npmplus/data" \
  "${DATA_DIR}/uptimekuma/data" \
  "${DATA_DIR}/dns/config" \
  "${DATA_DIR}/dns/logs" \
  "${DATA_DIR}/wireguard/config" \
  "${DATA_DIR}/wireguard/certs" \
  "${DATA_DIR}/wireshark/config" \
  "${DATA_DIR}/homarr/configs" \
  "${DATA_DIR}/homarr/icons" \
  "${DATA_DIR}/homarr/data" \
  "${DATA_DIR}/authentik/media" \
  "${DATA_DIR}/authentik/templates" \
  "${DATA_DIR}/authentik/geoip" \
  "${DATA_DIR}/postgresql" \
  "${DATA_DIR}/redis"; do
  mkdir -p "$d"
done

echo "[OK] Directories created"

# ==============================================================================
echo ""
echo "== 6. Generating .env =="

DNS_PW=$(randpw)
WIRESHARK_PW=$(randpw)
AUTHENTIK_SECRET=$(set +o pipefail; cat /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 50)
PG_PASS=$(randpw)

cat > "${COMPOSE_DIR}/.env" <<ENV
# Network Stack -- Environment Variables
# Generated by install.sh -- $(date '+%Y-%m-%d %H:%M:%S')

TZ=Europe/Ljubljana
PUID=1000
PGID=1000
DATA_DIR=${DATA_DIR}

SERVER_IP=${SERVER_IP}
DOMAIN=yourdomain.example.com

NPM_ADMIN_PORT=8070

DNS_WEB_PORT=8071
DNS_UDP_PORT=53
DNS_TCP_PORT=53
DNS_DOT_PORT=853
DNS_DOH_PORT=8053
DNS_ADMIN_PASSWORD=${DNS_PW}

UPTIMEKUMA_PORT=8072

WG_PORT=51820
WG_SUBNET=10.13.13.0
WG_PEERS=10
INTERNAL_SUBNET=192.168.1.0/24

# Wireshark uses network_mode: host -- listens directly on host port 3000
WIRESHARK_PASSWORD=${WIRESHARK_PW}

HOMARR_PORT=8074

AUTHENTIK_HTTP_PORT=9000
AUTHENTIK_HTTPS_PORT=9443
AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET}
PG_USER=authentik
PG_PASS=${PG_PASS}
PG_DB=authentik
ENV

chmod 600 "${COMPOSE_DIR}/.env"
echo "[OK] .env created with random passwords"

# ==============================================================================
echo ""
echo "== 7. Generating docker-compose.yml =="

cat > "${COMPOSE_DIR}/docker-compose.yml" <<COMPOSE
name: network-stack

networks:
  netstack:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  npm_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/npmplus/data
  dns_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/dns/config
  dns_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/dns/logs
  uptimekuma_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/uptimekuma/data
  wireguard_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wireguard/config
  wireshark_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wireshark/config
  homarr_configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/homarr/configs
  homarr_icons:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/homarr/icons
  homarr_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/homarr/data
  authentik_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/authentik/media
  authentik_templates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/authentik/templates
  authentik_geoip:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/authentik/geoip
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/postgresql
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/redis

services:

  # NPMplus -- Nginx Proxy Manager Plus
  # Note: no /etc/letsencrypt mount -- NPMplus manages certs inside /data
  npmplus:
    image: zoeyvid/npmplus:latest
    container_name: npmplus
    restart: unless-stopped
    networks: [netstack]
    ports:
      - "80:80"
      - "443:443"
      - "\${NPM_ADMIN_PORT}:81"
    volumes:
      - npm_data:/data
    environment:
      - TZ=\${TZ}
    cap_add: [NET_ADMIN, NET_BIND_SERVICE]

  # Technitium DNS Server
  dns:
    image: technitium/dns-server:latest
    container_name: technitium-dns
    restart: unless-stopped
    networks: [netstack]
    ports:
      - "\${DNS_WEB_PORT}:5380"
      - "\${DNS_UDP_PORT}:53/udp"
      - "\${DNS_TCP_PORT}:53/tcp"
      - "\${DNS_DOT_PORT}:853"
      - "\${DNS_DOH_PORT}:8053"
    volumes:
      - dns_config:/etc/dns
      - dns_logs:/var/log/dns
    environment:
      - TZ=\${TZ}
      - DNS_SERVER_DOMAIN=\${DOMAIN}
      - DNS_SERVER_ADMIN_PASSWORD=\${DNS_ADMIN_PASSWORD}

  # Uptime Kuma -- service monitoring dashboard
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    restart: unless-stopped
    networks: [netstack]
    ports:
      - "\${UPTIMEKUMA_PORT}:3001"
    volumes:
      - uptimekuma_data:/app/data
    environment:
      - TZ=\${TZ}

  # WireGuard -- VPN server (10 client configs auto-generated on first boot)
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    networks: [netstack]
    ports:
      - "\${WG_PORT}:51820/udp"
    volumes:
      - wireguard_config:/config
    environment:
      - PUID=\${PUID}
      - PGID=\${PGID}
      - TZ=\${TZ}
      - SERVERURL=\${SERVER_IP}
      - SERVERPORT=\${WG_PORT}
      - PEERS=\${WG_PEERS}
      - PEERDNS=auto
      - INTERNAL_SUBNET=\${WG_SUBNET}
      - ALLOWEDIPS=0.0.0.0/0,::/0
      - PERSISTENTKEEPALIVE=25
      - LOG_CONFS=true
    cap_add: [NET_ADMIN, SYS_MODULE]
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1

  # Wireshark -- browser-accessible packet capture
  # IMPORTANT: network_mode=host means port mapping is ignored.
  # The web UI is accessible directly on host port 3000.
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    restart: unless-stopped
    network_mode: host
    cap_add: [NET_ADMIN]
    volumes:
      - wireshark_config:/config
    environment:
      - PUID=\${PUID}
      - PGID=\${PGID}
      - TZ=\${TZ}
      - CUSTOM_USER=admin
      - PASSWORD=\${WIRESHARK_PASSWORD}

  # Homarr -- homepage / service dashboard
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    networks: [netstack]
    ports:
      - "\${HOMARR_PORT}:7575"
    volumes:
      - homarr_configs:/app/data/configs
      - homarr_icons:/app/public/icons
      - homarr_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=\${TZ}
      - BASE_URL=http://\${SERVER_IP}:\${HOMARR_PORT}

  # PostgreSQL -- database backend for Authentik
  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: postgresql
    restart: unless-stopped
    networks: [netstack]
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=\${PG_PASS}
      - POSTGRES_USER=\${PG_USER}
      - POSTGRES_DB=\${PG_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d \${PG_DB} -U \${PG_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  # Redis -- cache/broker backend for Authentik
  redis:
    image: docker.io/library/redis:alpine
    container_name: redis
    restart: unless-stopped
    networks: [netstack]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s

  # Authentik -- identity provider / SSO
  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-server
    restart: unless-stopped
    networks: [netstack]
    command: server
    ports:
      - "\${AUTHENTIK_HTTP_PORT}:9000"
      - "\${AUTHENTIK_HTTPS_PORT}:9443"
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
      - authentik_geoip:/geoip
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=\${PG_USER}
      - AUTHENTIK_POSTGRESQL__PASSWORD=\${PG_PASS}
      - AUTHENTIK_POSTGRESQL__NAME=\${PG_DB}
      - AUTHENTIK_SECRET_KEY=\${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=false
      - TZ=\${TZ}
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Authentik worker -- background task processor
  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    restart: unless-stopped
    networks: [netstack]
    command: worker
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
      - authentik_geoip:/geoip
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=\${PG_USER}
      - AUTHENTIK_POSTGRESQL__PASSWORD=\${PG_PASS}
      - AUTHENTIK_POSTGRESQL__NAME=\${PG_DB}
      - AUTHENTIK_SECRET_KEY=\${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=false
      - TZ=\${TZ}
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
COMPOSE

# WireGuard client cert symlink helper
cat > "${COMPOSE_DIR}/link-wg-certs.sh" <<'LINKSH'
#!/usr/bin/env bash
DATA_DIR="/home/networkder_data"
CERT_DIR="${DATA_DIR}/wireguard/certs"
CONFIG_DIR="${DATA_DIR}/wireguard/config"
for i in $(seq 1 10); do
  PEER="peer${i}"
  if [ -d "${CONFIG_DIR}/${PEER}" ]; then
    ln -sfn "${CONFIG_DIR}/${PEER}" "${CERT_DIR}/${PEER}"
    echo "[OK] Linked: ${CERT_DIR}/${PEER}"
  fi
done
echo "[i] Client .conf and QR PNG files are in ${CERT_DIR}/"
LINKSH
chmod +x "${COMPOSE_DIR}/link-wg-certs.sh"

echo "[OK] docker-compose.yml created"

# ==============================================================================
echo ""
echo "== 8. Configuring firewall =="

ufw allow 22/tcp    comment "SSH"           > /dev/null 2>&1
ufw allow 80/tcp    comment "HTTP"          > /dev/null 2>&1
ufw allow 443/tcp   comment "HTTPS"         > /dev/null 2>&1
ufw allow 8070/tcp  comment "NPMplus Admin" > /dev/null 2>&1
ufw allow 8071/tcp  comment "DNS Web UI"    > /dev/null 2>&1
ufw allow 53        comment "DNS"           > /dev/null 2>&1
ufw allow 8072/tcp  comment "Uptime Kuma"   > /dev/null 2>&1
ufw allow 51820/udp comment "WireGuard"     > /dev/null 2>&1
ufw allow 3000/tcp  comment "Wireshark"     > /dev/null 2>&1
ufw allow 8074/tcp  comment "Homarr"        > /dev/null 2>&1
ufw allow 9000/tcp  comment "Authentik HTTP"  > /dev/null 2>&1
ufw allow 9443/tcp  comment "Authentik HTTPS" > /dev/null 2>&1
echo "[OK] UFW rules added"

# ==============================================================================
echo ""
echo "== 9. Removing old stack and volumes if present =="

cd "${COMPOSE_DIR}"
docker compose down --volumes 2>/dev/null || true
echo "[OK] Old stack removed"

# ==============================================================================
echo ""
echo "== 10. Starting services =="

docker compose --env-file "${COMPOSE_DIR}/.env" up -d
echo "[OK] All services started"

# ==============================================================================
echo ""
echo "== 11. Summary =="
echo ""
echo "+----------------------------------------------------------+"
echo "|         Network Stack -- Installed Services              |"
echo "+----------------------------------------------------------+"
printf "| %-18s  http://%-33s|\n" "NPMplus Admin"  "${SERVER_IP}:8070"
printf "| %-18s  http://%-33s|\n" "Technitium DNS" "${SERVER_IP}:8071"
printf "| %-18s  http://%-33s|\n" "Uptime Kuma"    "${SERVER_IP}:8072"
printf "| %-18s  udp://%-33s|\n"  "WireGuard"      "${SERVER_IP}:51820"
printf "| %-18s  https://%-32s|\n" "Wireshark"      "${SERVER_IP}:3000  (self-signed)"
printf "| %-18s  http://%-33s|\n" "Homarr"         "${SERVER_IP}:8074"
printf "| %-18s  http://%-33s|\n" "Authentik"      "${SERVER_IP}:9000"
echo "+----------------------------------------------------------+"
printf "| DNS admin password:  %-36s|\n" "${DNS_PW}"
printf "| Wireshark password:  %-36s|\n" "${WIRESHARK_PW}"
printf "| Authentik secret:    %-36s|\n" "${AUTHENTIK_SECRET:0:24}..."
printf "| PostgreSQL password: %-36s|\n" "${PG_PASS}"
echo "+----------------------------------------------------------+"
printf "| .env:    %-47s|\n" "${COMPOSE_DIR}/.env"
printf "| Compose: %-47s|\n" "${COMPOSE_DIR}/docker-compose.yml"
printf "| Data:    %-47s|\n" "${DATA_DIR}/"
echo "+----------------------------------------------------------+"
echo ""
echo "[!] Edit ${COMPOSE_DIR}/.env -- set DOMAIN and INTERNAL_SUBNET (your LAN)."
echo "[!] Forward UDP 51820 on your router to ${SERVER_IP} for WireGuard."
echo "[!] After WireGuard starts, run: ${COMPOSE_DIR}/link-wg-certs.sh"
echo "[!] Wireshark: odpri https://${SERVER_IP}:3000 -- self-signed cert, sprejmi opozorilo v brskalniku."
echo "[!] .env contains secrets -- do not commit it to git."
echo "[!] Authentik: first-time setup wizard je na http://${SERVER_IP}:9000/if/flow/initial-setup/"
echo ""
echo "[OK] Installation complete."
